name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: macOS ARM
            label: darwin-arm64
            os: macos-26
          - name: macOS Intel
            label: darwin-x64
            os: macos-26
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          check-latest: true
      - name: Install dependencies
        run: yarn install

      # OSX Sign
      - name: Set up keychain and import signing certificate
        if: matrix.label == 'darwin-arm64' || matrix.label == 'darwin-x64'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.OSX_CERT_P12 }}
          p12-password: ${{ secrets.OSX_CERT_PASSWORD }}
      - name: Set signin environment
        if: matrix.label == 'darwin-arm64' || matrix.label == 'darwin-x64'
        run: |
          echo "OSX_SIGN_ENABLED=true" >> $GITHUB_ENV
          echo "OSX_SIGN_IDENTITY=${{ secrets.OSX_SIGN_IDENTITY }}" >> $GITHUB_ENV
          echo "OSX_NOTARIZE_ENABLED=true" >> $GITHUB_ENV
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "APPLE_ID_PASSWORD=${{ secrets.APPLE_ID_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV

      - name: Run build (macOS ARM)
        if: matrix.label == 'darwin-arm64'
        run: |
          yarn make:macos
          mv out/make/zip/darwin/arm64/** out/keep/

      - name: Run build (macOS Intel)
        if: matrix.label == 'darwin-x64'
        run: |
          yarn make:macos-intel
          mv out/make/zip/darwin/x64/** out/keep/

      - name: Get package version
        id: get_version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}
          path: out/keep/**
