name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS ARM
            label: darwin-arm64
            os: macos-26
          - name: macOS Intel
            label: darwin-x64
            os: macos-26
          - name: Windows 32-bit
            label: win-ia32
            os: ubuntu-24.04
          - name: Windows 64-bit
            label: win-x64
            os: ubuntu-24.04
          - name: Linux 64-bit
            label: linux-x64
            os: ubuntu-24.04
          - name: Linux ARM
            label: linux-arm64
            os: ubuntu-24.04-arm
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          check-latest: true
      - name: Install dependencies
        run: yarn install
      - name: Create output directory
        run: mkdir -p out/keep

      # OSX Sign
      - name: Set up keychain and import signing certificate
        if: matrix.label == 'darwin-arm64' || matrix.label == 'darwin-x64'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.OSX_CERT_P12 }}
          p12-password: ${{ secrets.OSX_CERT_PASSWORD }}
      - name: Set signin environment
        if: matrix.label == 'darwin-arm64' || matrix.label == 'darwin-x64'
        run: |
          echo "OSX_SIGN_ENABLED=true" >> $GITHUB_ENV
          echo "OSX_SIGN_IDENTITY=${{ secrets.OSX_SIGN_IDENTITY }}" >> $GITHUB_ENV
          echo "OSX_NOTARIZE_ENABLED=true" >> $GITHUB_ENV
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "APPLE_ID_PASSWORD=${{ secrets.APPLE_ID_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV
      - name: Get package version
        id: get_version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Run build (macOS ARM)
        if: matrix.label == 'darwin-arm64'
        run: |
          yarn make:macos
          mv out/make/zip/darwin/arm64/*.zip out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.zip

      - name: Run build (macOS Intel)
        if: matrix.label == 'darwin-x64'
        run: |
          yarn make:macos-intel
          mv out/make/zip/darwin/x64/*.zip out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.zip

      - name: Run build (Windows 32-bit)
        if: matrix.label == 'win-ia32'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install wine wine64 mono-devel
          export PATH=$PATH:/usr/lib/wine
          yarn make:win-32bit
          mv out/make/zip/win32/ia32/*.zip out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.zip
          mv out/make/squirrel.windows/ia32 out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}-squirrel
      
      - name: Run build (Windows 64-bit)
        if: matrix.label == 'win-x64'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install wine64 mono-devel
          export PATH=$PATH:/usr/lib/wine
          yarn make:win
          mv out/make/zip/win32/x64/*.zip out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.zip
          mv out/make/squirrel.windows/x64 out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}-squirrel

      - name: Run build (Linux ARM64)
        if: matrix.label == 'linux-arm64'
        run: |
          yarn make:linux-arm64
          mv out/make/deb/arm64/*.deb out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.deb
          mv out/make/rpm/arm64/*.rpm out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.rpm
          mv out/make/AppImage/arm64/*.AppImage out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.AppImage

      - name: Run build (Linux 64-bit)
        if: matrix.label == 'linux-x64'
        run: |
          yarn make:linux
          mv out/make/deb/x64/*.deb out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.deb
          mv out/make/rpm/x64/*.rpm out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.rpm
          mv out/make/AppImage/x64/*.AppImage out/keep/gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}.AppImage

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gba-studio-${{ env.PACKAGE_VERSION }}-${{ matrix.label }}
          path: |
            ./out/keep/**
